# Generated by Django 3.2.13 on 2022-05-25 01:39

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_rename_game_id_game_gameid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.CharField(blank=True, max_length=700, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/jojocloudci/image/upload/v1653441917/default-profile_fb2lrf.jpg', max_length=255, verbose_name='image')),
                ('played', models.ManyToManyField(related_name='played', to='game.Game')),
                ('to_play', models.ManyToManyField(related_name='to_play', to='game.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
