# Generated by Django 3.2.13 on 2022-05-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_review_reviewid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewID',
        ),
    ]
